export const categories = ['All', 'Core', 'UI', 'Utilities'];

export const tools = [
  {
    id: 'component-kit',
    name: 'Component Kit',
    category: 'Core',
    status: 'Available',
    description:
      'Reusable components and managers for building interfaces with vanilla JavaScript.',
    repository: 'https://github.com/Peccopa/component-kit',
    image: '/rsschool-landing-page/images/component-kit.webp',
    icon: 'component',
  },
  {
    id: 'state-kit',
    name: 'State Kit',
    category: 'Core',
    status: 'Available',
    description:
      'Lightweight state management with reducers, middleware and subscriptions.',
    repository: 'https://github.com/Peccopa/state-kit',
    image: '/rsschool-landing-page/images/state-kit.webp',
    icon: 'state',
  },
  {
    id: 'router-kit',
    name: 'Router Kit',
    category: 'Core',
    status: 'Available',
    description: 'Simple client-side routing for JavaScript applications.',
    repository: 'https://github.com/Peccopa/router-kit',
    image: '/rsschool-landing-page/images/router-kit.webp',
    icon: 'router',
  },
  {
    id: 'sound-kit',
    name: 'Sound Kit',
    category: 'Core',
    status: 'Available',
    description: 'Reusable sound and audio utilities for web applications.',
    repository: 'https://github.com/Peccopa',
    image: '/rsschool-landing-page/images/sound-kit.webp',
    icon: 'sound',
  },
  {
    id: 'i18n-kit',
    name: 'i18n Kit',
    category: 'Core',
    status: 'Available',
    description: 'Simple internationalization utilities for web projects.',
    repository: 'https://github.com/Peccopa',
    image: '/rsschool-landing-page/images/i18n-kit.webp',
    icon: 'i18n',
  },
  {
    id: 'js-starter-pack',
    name: 'JS Starter Pack',
    category: 'Core',
    status: 'Available',
    description: 'A ready-to-use JavaScript project foundation.',
    repository: 'https://github.com/Peccopa/js-starter-pack',
    image: '/rsschool-landing-page/images/js-starter-pack.webp',
    icon: 'javascript',
  },
  {
    id: 'ts-starter-pack',
    name: 'TS Starter Pack',
    category: 'Core',
    status: 'Available',
    description: 'A ready-to-use TypeScript project foundation.',
    repository: 'https://github.com/Peccopa/ts-starter-pack',
    image: '/rsschool-landing-page/images/ts-starter-pack.webp',
    icon: 'typescript',
  },
  {
    id: 'ui-kit',
    name: 'UI Kit',
    category: 'UI',
    status: 'In development',
    description: 'Reusable interface components for web projects.',
    repository: 'https://github.com/Peccopa',
    image: '/rsschool-landing-page/images/ui-kit.webp',
    icon: 'ui',
  },
  {
    id: 'style-kit',
    name: 'Style Kit',
    category: 'Core',
    status: 'Planned',
    description: 'Reusable styling utilities for web projects.',
    repository: 'https://github.com/Peccopa',
    image: '/rsschool-landing-page/images/style-kit.webp',
    icon: 'style',
  },
  {
    id: 'modal-kit',
    name: 'Modal Kit',
    category: 'UI',
    status: 'Planned',
    description:
      'Reusable modal, dialog and overlay components for web projects.',
    repository: 'https://github.com/Peccopa',
    image: '/rsschool-landing-page/images/modal-kit.webp',
    icon: 'modal',
  },
  {
    id: 'format-kit',
    name: 'Format Kit',
    category: 'Utilities',
    status: 'Planned',
    description:
      'Reusable utilities for formatting dates, numbers, strings and common data types.',
    repository: 'https://github.com/Peccopa',
    image: '/rsschool-landing-page/images/placeholder.webp',
    icon: 'format',
  },
];
